export const USE_CASES = [
  {
    id: 'lead_scoring',
    label: 'Lead Scoring Enhancement',
    description: 'Sync warehouse data to CRM for predictive lead scoring',
    defaultTimeSaved: 8,
    defaultRevImpact: 3,
    defaultChurnReduction: 0,
    icon: 'Crosshair',
  },
  {
    id: 'customer_360',
    label: 'Customer 360 for Sales',
    description: 'Sync product usage data to Salesforce for full context',
    defaultTimeSaved: 6,
    defaultRevImpact: 5,
    defaultChurnReduction: 0,
    icon: 'Users',
  },
  {
    id: 'audience_sync',
    label: 'Marketing Audience Sync',
    description: 'Sync segments to ad platforms and email tools',
    defaultTimeSaved: 10,
    defaultRevImpact: 4,
    defaultChurnReduction: 0,
    icon: 'Megaphone',
  },
  {
    id: 'plg_signals',
    label: 'Product-Led Growth Signals',
    description: 'Sync PQL scores and usage signals to sales tools',
    defaultTimeSaved: 4,
    defaultRevImpact: 6,
    defaultChurnReduction: 0,
    icon: 'Rocket',
  },
  {
    id: 'health_scoring',
    label: 'Customer Health Scoring',
    description: 'Sync usage data to CS platforms for proactive retention',
    defaultTimeSaved: 5,
    defaultRevImpact: 0,
    defaultChurnReduction: 10,
    icon: 'HeartPulse',
  },
  {
    id: 'rev_ops',
    label: 'Revenue Operations',
    description: 'Automated reporting, data hygiene, and ops workflows',
    defaultTimeSaved: 15,
    defaultRevImpact: 2,
    defaultChurnReduction: 0,
    icon: 'Settings',
  },
]

export const INDUSTRIES = ['SaaS', 'E-commerce', 'Financial Services', 'Healthcare', 'Media', 'Other']
export const WAREHOUSES = ['Snowflake', 'BigQuery', 'Databricks', 'Redshift', 'Other']
export const CURRENT_STATES = ['Manual CSV exports', 'Custom scripts', 'Another tool', 'Nothing — no syncing today']
export const COMPANY_SIZES = ['1-50', '51-200', '201-500', '501-1000', '1000-5000', '5000+']

export const INDUSTRY_BENCHMARKS = {
  SaaS: { timeSavings: 22, revImpact: 5.2, avgROI: 14 },
  'E-commerce': { timeSavings: 18, revImpact: 4.8, avgROI: 12 },
  'Financial Services': { timeSavings: 25, revImpact: 3.5, avgROI: 11 },
  Healthcare: { timeSavings: 20, revImpact: 3.0, avgROI: 10 },
  Media: { timeSavings: 15, revImpact: 6.0, avgROI: 13 },
  Other: { timeSavings: 18, revImpact: 4.0, avgROI: 11 },
}

export const SAVED_REPORTS = [
  {
    id: 1,
    prospect: 'TechCorp',
    industry: 'SaaS',
    ae: 'Kevin Park',
    created: '2025-01-15',
    totalValue: 698000,
    censusCost: 42000,
    roiRatio: 16.6,
    dealStage: 'Negotiation',
    dealAmount: 42000,
    status: 'Sent',
    useCases: ['Lead Scoring', 'Customer 360', 'RevOps'],
    scenario: 'Moderate',
  },
  {
    id: 2,
    prospect: 'ShopifyPlus Merchant',
    industry: 'E-commerce',
    ae: 'Sophia Chen',
    created: '2025-01-22',
    totalValue: 312000,
    censusCost: 24000,
    roiRatio: 13.0,
    dealStage: 'Proposal',
    dealAmount: 24000,
    status: 'Sent',
    useCases: ['Audience Sync', 'PLG Signals'],
    scenario: 'Moderate',
  },
  {
    id: 3,
    prospect: 'Pacific Life',
    industry: 'Financial Services',
    ae: 'Daniel Okafor',
    created: '2025-02-03',
    totalValue: 1200000,
    censusCost: 96000,
    roiRatio: 12.5,
    dealStage: 'Discovery',
    dealAmount: 96000,
    status: 'Draft',
    useCases: ['Lead Scoring', 'Customer 360', 'Health Scoring', 'RevOps'],
    scenario: 'Conservative',
  },
  {
    id: 4,
    prospect: 'HealthFirst System',
    industry: 'Healthcare',
    ae: 'Lena Müller',
    created: '2025-02-10',
    totalValue: 445000,
    censusCost: 36000,
    roiRatio: 12.4,
    dealStage: 'Closed Won',
    dealAmount: 36000,
    status: 'Presented',
    useCases: ['Customer 360', 'Health Scoring'],
    scenario: 'Conservative',
  },
  {
    id: 5,
    prospect: 'StreamMedia',
    industry: 'Media',
    ae: 'Kevin Park',
    created: '2025-02-18',
    totalValue: 520000,
    censusCost: 48000,
    roiRatio: 10.8,
    dealStage: 'Proposal',
    dealAmount: 48000,
    status: 'Sent',
    useCases: ['Audience Sync', 'PLG Signals', 'RevOps'],
    scenario: 'Moderate',
  },
  {
    id: 6,
    prospect: 'Acme SaaS Corp',
    industry: 'SaaS',
    ae: 'Sophia Chen',
    created: '2025-03-01',
    totalValue: 890000,
    censusCost: 60000,
    roiRatio: 14.8,
    dealStage: 'Negotiation',
    dealAmount: 60000,
    status: 'Presented',
    useCases: ['Lead Scoring', 'Customer 360', 'PLG Signals', 'RevOps'],
    scenario: 'Moderate',
  },
  {
    id: 7,
    prospect: 'RetailMax',
    industry: 'E-commerce',
    ae: 'Daniel Okafor',
    created: '2025-03-05',
    totalValue: 275000,
    censusCost: 30000,
    roiRatio: 9.2,
    dealStage: 'Discovery',
    dealAmount: 30000,
    status: 'Draft',
    useCases: ['Audience Sync'],
    scenario: 'Conservative',
  },
  {
    id: 8,
    prospect: 'FinServe Global',
    industry: 'Financial Services',
    ae: 'Kevin Park',
    created: '2025-03-12',
    totalValue: 1450000,
    censusCost: 120000,
    roiRatio: 12.1,
    dealStage: 'Proposal',
    dealAmount: 120000,
    status: 'Sent',
    useCases: ['Lead Scoring', 'Customer 360', 'Health Scoring', 'RevOps'],
    scenario: 'Moderate',
  },
  {
    id: 9,
    prospect: 'MedTech Solutions',
    industry: 'Healthcare',
    ae: 'Lena Müller',
    created: '2025-03-20',
    totalValue: 380000,
    censusCost: 36000,
    roiRatio: 10.6,
    dealStage: 'Closed Won',
    dealAmount: 36000,
    status: 'Presented',
    useCases: ['Customer 360', 'RevOps'],
    scenario: 'Moderate',
  },
  {
    id: 10,
    prospect: 'BrightMedia Group',
    industry: 'Media',
    ae: 'Sophia Chen',
    created: '2025-03-28',
    totalValue: 620000,
    censusCost: 54000,
    roiRatio: 11.5,
    dealStage: 'Negotiation',
    dealAmount: 54000,
    status: 'Sent',
    useCases: ['Audience Sync', 'PLG Signals', 'Health Scoring'],
    scenario: 'Aggressive',
  },
  {
    id: 11,
    prospect: 'CloudOps Inc',
    industry: 'SaaS',
    ae: 'Daniel Okafor',
    created: '2025-04-02',
    totalValue: 540000,
    censusCost: 36000,
    roiRatio: 15.0,
    dealStage: 'Discovery',
    dealAmount: 36000,
    status: 'Draft',
    useCases: ['Lead Scoring', 'PLG Signals'],
    scenario: 'Moderate',
  },
  {
    id: 12,
    prospect: 'QuickShip Logistics',
    industry: 'E-commerce',
    ae: 'Kevin Park',
    created: '2025-04-08',
    totalValue: 410000,
    censusCost: 42000,
    roiRatio: 9.8,
    dealStage: 'Proposal',
    dealAmount: 42000,
    status: 'Sent',
    useCases: ['Audience Sync', 'Customer 360', 'RevOps'],
    scenario: 'Conservative',
  },
  {
    id: 13,
    prospect: 'NexGen Financial',
    industry: 'Financial Services',
    ae: 'Lena Müller',
    created: '2025-04-15',
    totalValue: 980000,
    censusCost: 84000,
    roiRatio: 11.7,
    dealStage: 'Closed Won',
    dealAmount: 84000,
    status: 'Presented',
    useCases: ['Lead Scoring', 'Customer 360', 'RevOps'],
    scenario: 'Moderate',
  },
  {
    id: 14,
    prospect: 'Wellness360',
    industry: 'Healthcare',
    ae: 'Sophia Chen',
    created: '2025-04-22',
    totalValue: 290000,
    censusCost: 24000,
    roiRatio: 12.1,
    dealStage: 'Discovery',
    dealAmount: 24000,
    status: 'Draft',
    useCases: ['Health Scoring', 'RevOps'],
    scenario: 'Moderate',
  },
  {
    id: 15,
    prospect: 'Vibe Studios',
    industry: 'Media',
    ae: 'Daniel Okafor',
    created: '2025-05-01',
    totalValue: 475000,
    censusCost: 42000,
    roiRatio: 11.3,
    dealStage: 'Proposal',
    dealAmount: 42000,
    status: 'Draft',
    useCases: ['Audience Sync', 'Customer 360', 'PLG Signals'],
    scenario: 'Aggressive',
  },
]
